<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mauren.Discord.Application\Mauren.Discord.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\img\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mauren.AspNetCore.Mvc.Components" Version="0.1.0" />
    <PackageReference Include="Mauren.AspNetCore.Mvc.TagHelpers" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\img\Discord-Logo-Blurple.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\img\Discord-Logo-Blurple.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\img\Discord-Symbol-Blurple.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot\img\Discord-Symbol-Blurple.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
